# Generated by Django 4.0 on 2022-07-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('hist_date', models.DateField(auto_now_add=True)),
                ('hist_img_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='leaf_dis',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=45)),
                ('disease_look', models.TextField(max_length=1000)),
                ('disease_epidemic', models.TextField(max_length=1000)),
                ('disease_prevent', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='leaf_images',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
