# Generated by Django 4.0 on 2022-07-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_history_leaf_dis_leaf_images_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf_images',
            name='img_ord',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
