# Generated by Django 4.0 on 2022-07-24 11:33

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_leaf_images_img_ord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf_images',
            name='img_ord',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.filepath),
        ),
    ]
