# Generated by Django 4.0 on 2022-07-24 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_leaf_images_img_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf_images',
            name='img_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
