# Generated by Django 4.0 on 2022-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_leaf_images_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf_dis',
            name='disease_id',
            field=models.IntegerField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
