# Generated by Django 4.0 on 2022-07-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_leaf_dis_disease_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf_dis',
            name='disease_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
