# Generated by Django 4.0 on 2022-07-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogs', '0009_alter_leaf_dis_disease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf_images',
            name='user1',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
