# Generated by Django 4.0 on 2022-07-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_leaf_images_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaf_images',
            old_name='img_ord',
            new_name='img_leaf',
        ),
    ]
