# Generated by Django 4.0 on 2022-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_rename_img_ord_leaf_images_img_leaf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaf_images',
            name='user1',
        ),
        migrations.AlterField(
            model_name='leaf_images',
            name='img_leaf',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
