# Generated by Django 4.0 on 2022-07-25 14:23

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_remove_leaf_images_user1_alter_leaf_images_img_leaf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaf_images',
            name='img_leaf',
        ),
        migrations.AddField(
            model_name='leaf_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.filepath),
        ),
    ]
