# Generated by Django 4.0 on 2022-08-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_remove_leaf_images_img_leaf_leaf_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf_dis',
            name='disease_name',
            field=models.CharField(max_length=200),
        ),
    ]
