# Generated by Django 4.0 on 2022-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_leaf_dis_disease_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf_dis',
            name='disease_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
