# Generated by Django 4.0 on 2022-08-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_leaf_dis_disease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf_dis',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaf_dis',
            name='disease_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
