# Generated by Django 4.0 on 2022-08-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_leaf_dis_datecreated_alter_leaf_dis_disease_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf_dis',
            name='disease_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
