# Generated by Django 4.0 on 2022-09-18 14:32

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_history_disease1_history_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='hist_img_path',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.filepath),
        ),
    ]
