# Generated by Django 4.0 on 2022-09-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogs', '0019_alter_history_hist_img_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history',
            new_name='historys',
        ),
    ]
