# Generated by Django 4.0 on 2022-09-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogs', '0021_remove_historys_disease1_remove_historys_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='historys',
            name='user1',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
