# Generated by Django 4.0 on 2022-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_alter_historys_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='historys',
            name='pub_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
