# Generated by Django 4.0 on 2022-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_remove_historys_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historys',
            name='pub_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
