# Generated by Django 4.0 on 2022-10-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_historys_scored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historys',
            old_name='scoreD',
            new_name='scoreDisease',
        ),
    ]
