# Generated by Django 4.0 on 2022-10-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_rename_scored_historys_scoredisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historys',
            name='scoreDisease',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
