# Generated by Django 4.0 on 2022-10-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_alter_historys_scoredisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historys',
            name='scoreDisease',
            field=models.DecimalField(decimal_places=2, max_digits=3, max_length=200, null=True),
        ),
    ]
